dependencies:
  - python=3
  - pip:
    - akshare==1.6.8
    - beautifulsoup4==4.11.1
    - docx==0.2.4
    - hanlp==2.1.0b41
    - ipykernel==6.13.0
    - ipystata==0.3.8
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - itsdangerous==2.1.2
    - KDEpy==1.1.0
    - keras==2.9.0
    - kmodes==0.12.2
    - Markdown==3.3.7
    - matplotlib==3.5.2
    - networkx==2.8.2
    - numpy==1.22.4
    - openpyxl==3.0.10
    - pandas==1.4.2
    - pandoc==2.2
    - pdfplumber==0.10.3
    - Pillow==10.0.1
    - polars==0.13.41
    - prettytable==3.10.0
    - PyAstronomy==0.17.1
    - PyPDF2==2.4.2
    - PyQt5==5.15.10
    - requests==2.27.1
    - scikit-learn==1.1.1
    - scikit-opt==0.6.6
    - scipy==1.8.1
    - seaborn==0.11.2
    - stats==0.1.2a0
    - statsmodels==0.13.2
    - tabulate==0.8.9
    - tensorboard==2.9.0
    - tensorflow==2.9.1
    - torch==1.11.0
    - tqdm==4.64.0
    - xgboost==1.6.1
    - xlrd==2.0.1
